// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DataTableController from "./data_table_controller"
application.register("data-table", DataTableController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import LoginController from "./login_controller"
application.register("login", LoginController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import Ts__SelectController from "./ts/select_controller"
application.register("ts--select", Ts__SelectController)

import WorkOrderWidgetController from "./work_order_widget_controller"
application.register("work-order-widget", WorkOrderWidgetController)

import WorkOrderDateController from "./work_order_date_controller"
application.register("work-order-date", WorkOrderDateController)
