require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  #- rubocop-rake
  - rubocop-thread_safety
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - config/navigation.rb
  #Max: 50
MethodLength:
  Max: 35
Metrics/AbcSize:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - rubocop/*
    - vendor/**/*
    - gemfiles/vendor/bundle/**/*
    - vendor/bundle/**/*
    - db/schema.rb
    - spec/**/*
    - spec/*
    - config/initializers/devise.rb
