require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  #- rubocop-rake
  - rubocop-thread_safety
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - rubocop/*
    - vendor/**/*
    - gemfiles/vendor/bundle/**/*
    - vendor/bundle/**/*
    - db/schema.rb
    - spec/**/*
    - spec/*
