require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  #- rubocop-rake
  - rubocop-thread_safety
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Exclude:
    - app/controllers/application_controller.rb
    - config/initializers/devise.rb
Metrics/AbcSize:
  Exclude:
    - app/controllers/application_controller.rb
Metrics/BlockLength:
  Exclude:
    - config/navigation.rb
  #Max: 50
Metrics/MethodLength:
  Exclude:
    - db/migrate/20220911194444_devise_create_users.rb
    - db/migrate/20221006171930_create_work_order.rb
AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - rubocop/*
    - vendor/**/*
    - gemfiles/vendor/bundle/**/*
    - vendor/bundle/**/*
    - db/schema.rb
    - spec/**/*
    - spec/*
    - config/initializers/simple_form_bootstrap.rb
    - config/initializers/simple_form.rb
