version: "3.3"

volumes:
  db-data:
    driver: local

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  app:
    image: afaraldo/fleet-management-system:latest
    depends_on:
      - db
    ports:
      - "80:3000"
    env_file:
      - .env.production
    environment:
      DATABASE_URL: "postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db/${DATABASE_NAME}"
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: true