version: "3.3"

volumes:
  db-data:
    driver: local

  app:
    image: afaraldo/fleet-management-system:latest
    depends_on:
      - db
    ports:
      - "80:3000"
    env_file:
      - .env.production
    environment:
      DATABASE_URL: "postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "yes"