version: "3.3"

volumes:
  db-data:
  public-data:

services:
#  db:
#    image: postgres
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=${DATABASE_USER}
#      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
#      - POSTGRES_DB=${DATABASE_NAME}
#    ports:
#      - '5432:5432'
  app:
    image: afaraldo/fleet-management-system:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    volumes:
      - public-data:/app/public
      - ./log/production.log:/app/log/production.log
    environment:
      DATABASE_URL: "postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "yes"
#  haproxy:
#    image: haproxy:latest
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
#      - ./localhost.pem:/etc/ssl/localhost.pem:ro
#    depends_on:
#      - app