# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
# Tests
name: "Ruby on Rails CI"
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'     # excludes main
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
      RAILS_MASTER_KEY: 7343f73082e5afc1a717137af3b0462e
      token: "${{ secrets.GH_PERSONAL_TOKEN }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          bundler-cache: true
          token: "${{ secrets.GH_PERSONAL_TOKEN }}"
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          token: "${{ secrets.GH_PERSONAL_TOKEN }}"
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
      # Run migrations to database
      - name: Set up database schema
        run: bin/rails db:migrate
      # Add or replace database setup steps here
      - name: Set up database System Setting
        run: bin/rails system_settings:load RAILS_ENV=test
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@904f3fef85a9c80a3750cbe7d5159268fd5caa9f # v1.150
        with:
          bundler-cache: true
      # Add or replace any other lints here
      #  - name: Security audit dependencies
      #    run: bundle exec bundler-audit --update
      - name: Security audit application code
        run: bundle exec brakeman -q -w2
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
